project_id = "ydqrorzkrwesnehagfdx"

[functions.send-appointment-reminders]
verify_jwt = false

[functions.symptom-checker]
verify_jwt = false

[functions.wizy-agent]
verify_jwt = false

[functions.generate-health-tips]
verify_jwt = false
